name: Autoapprove PRs that contain only commits that exist in QA.

on:
    pull_request_target:
        types: [opened, synchronize, reopened]
        branches:
            - 'main'

jobs:
    auto-approve:
        name: Approve PRs if they only contain commits in QA
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write
        steps:  
            - uses: rnordmanASU/conditionally-approve-pr-containing-only-trusted-commits@main
              with:
                trusted-branches: 'mule-qa'
